### ISSUE TITLE
How to export to nist file

### ISSUE THREAD

**Issue by Suparuch** [kareez/jnbis#16]
I have a fingerprint image file type bmp, i want to convert to nist file.
pls to help me.

**Comment by abdoegy83** [comment]
i have WSQ files and i need to generate a NIST file 
Can you please help me on this

**Comment by kareez** [comment]
This library is just a decoder and, currently, there is no implementation of encoder functionality.
I've seen encoder implementation in some of the forks. you may use those forks. 

I would gladly accept pull requests for the encoder but, unfortunately, I don't have time to implement that myself.
