### ISSUE TITLE
how to convert file between wsq and png format

### ISSUE THREAD

**Issue by thisisnottaken** [kareez/jnbis#17]
sir ,
I am a newbie.
Please find attached the log after running 
mvn package
[31-mvn-package-in-jnbis.txt](https://github.com/kareez/jnbis/files/1932447/31-mvn-package-in-jnbis.txt)

My aim is to convert wsq file to png and vice versa.
i saw https://github.com/kareez/jnbis/blob/develop/README.md

Still , am unable to figure out . How to use the lines below ?

File png = Jnbis.wsq()
                .decode("path/to/wsq/file.wsq")
                .toPng()
                .asFile("/path/to/final/file.png");

All I understand is that I will put absolute file path for input and output in above.
But how to run the above command ? 

Thanks.

**Comment by ericdsoto** [comment]
thisisnottaken,

You need to create a Java class with that code and then compile and execute it. 

One very simple example might be the following:

```
import org.jnbis.api.Jnbis;
import java.io.File;

public class JnbisExample {
    public static void main(String[] args) {
        File png = Jnbis.wsq()
                .decode("path/to/wsq/file.wsq")
                .toPng()
                .asFile("/path/to/final/file.png");
        
        // do something with png file
    }
}
```
I hope this helps. Good luck!
-Eric

**Comment by thisisnottaken** [comment]
i saved above as JnbisExample.java
and ran java JnbisExample.java
Got 'Error: Could not find or load main class JnbisExample.java'

**Comment by ericdsoto** [comment]
You first need to compile the Java class using the Java compiler, **javac**. (Note the c at the end of the command.)

Something like:
```
javac -classpath /path/to/library/jnbis-2.0.0.jar JnbisExample.java
```
That will generate a JnbisExample.class file which you then can execute with the following command:
```
java -classpath ./:/path/to/library/lib/jnbis-2.0.0.jar JnbisExample
```

**Comment by thisisnottaken** [comment]
sir ,
That works.
Thanks a lot .

Is it possible to get wsq from png ?

**Comment by thisisnottaken** [comment]
Got it .
Installed nbis5_0_0 .
Can you tell which binary does png to wsq and vice versa among 

an2k2iaf  bozorth3  cjpegb     datainfo  djpegl    dwsq      histogen  lintran  mlp       oas2pics  pcasysx   rwpics    wrwsqcom
an2k2txt  chgdesc   cjpegl     diffbyts  djpeglsd  dwsq14    iaf2an2k  meancov  mlpfeats  optosf    rdimgwh   sd_rfmt   ycc2rgb
an2ktool  chkan2k   cmbmcs     djp2k     dlwsqcom  eva_evt   intr2not  mindtct  nfiq      optrws    rdjpgcom  stackms   znormdat
asc2bin   cjp2k     cropcoeff  djpeg     dpyan2k   fing2pat  jpegtran  mkoas    nfseg     optrwsgw  rdwsqcom  txt2an2k  znormpat
bin2asc   cjpeg     cwsq       djpegb    dpyimage  fixwts    kltran    mktran   not2intr  pcasys    rgb2ycc   wrjpgcom

**Comment by ericdsoto** [comment]
I am not terribly familiar with the binaries but my best bet would be to try the **an2ktool** under the an2k directory.
```
an2ktool - Parses, manipulates, and/or writes the results to an ANSI/NIST 2007 file in batch mode.
```
You could also look under **imgtools** for any binary that contains "wsq" in the name.

Finally, you can check out the **man** directory which contains a text (manual) file for each binary.

Best of luck!

**Comment by ericdsoto** [comment]
From page 15 of:  https://ws680.nist.gov/publication/get_pdf.cfm?pub_id=51097
> IMGTOOLS also contains a collection of standard compliant and certifiable image encoders and
> decoders. The utilities cjpegb and djpegb encode and decode Baseline JPEG files
> respectively. The utilities cjpegl and djpegl encode and decode Lossless JPEG files. This
> represents one of the only available implementations of the standard Lossless JPEG algorithm.
> Finally, the utilities **cwsq** and **dwsq** encode and decode FBI WSQ files. An X Window
> application, dpyimage, is provided to view these different file compression formats, including
> IHead images and raw pixmaps.

**Comment by Ortega-Dan** [comment]
> From page 15 of: https://ws680.nist.gov/publication/get_pdf.cfm?pub_id=51097
> 
> > IMGTOOLS also contains a collection of standard compliant and certifiable image encoders and
> > decoders. The utilities cjpegb and djpegb encode and decode Baseline JPEG files
> > respectively. The utilities cjpegl and djpegl encode and decode Lossless JPEG files. This
> > represents one of the only available implementations of the standard Lossless JPEG algorithm.
> > Finally, the utilities **cwsq** and **dwsq** encode and decode FBI WSQ files. An X Window
> > application, dpyimage, is provided to view these different file compression formats, including
> > IHead images and raw pixmaps.

I confirm, this actually does the job. If compiled, those binaries will help, and man pages are very helpful.

**Comment by gusciri** [comment]
Hi Eric, I'm running into an error while processing a specific image:
ArrayIndexOutOfBoundsException: Index 32767 out of bounds for length 32767
at:  org.jnbis.internal.WsqHelper$Token.readByte(WsqHelper.java:164)

Other images are working fine.

Thanks!
